export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'

export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const LOAD_TOKEN = 'LOAD_TOKEN'
export const LOAD_USER_ID = 'LOAD_USER_ID'
export const LOAD_COMPANY_ID = 'LOAD_COMPANY_ID'
export const LOAD_UNITS = 'LOAD_UNITS'
export const LOAD_LOCATIONS = 'LOAD_LOCATIONS'
export const LOAD_CHILD_LOCATIONS = 'LOAD_CHILD_LOCATIONS'

export const LOAD_ACTIVITIES = 'LOAD_ACTIVITIES'
export const LOAD_PLANNED_ACTIVITIES = 'LOAD_PLANNED_ACTIVITIES'
export const LOAD_ACTIVITY_DETAILS = 'LOAD_ACTIVITY_DETAILS'
export const LOAD_ACTIVITY_QUESTIONS = 'LOAD_ACTIVITY_QUESTIONS'
export const LOAD_UNIT_QUESIONS = 'LOAD_UNIT_QUESIONS'
export const LOAD_SITE_QUESTIONS = 'LOAD_SITE_QUESTIONS'

export const LOAD_STATIONS = 'LOAD_STATIONS'
export const LOAD_STATIONS_GRAPH = 'LOAD_STATIONS_GRAPH'

export const LOAD_EXTENDED_UNITS = 'LOAD_EXTENDED_UNITS'
export const LOAD_UNIT_REPORTS = 'LOAD_UNIT_REPORTS'

export const LOAD_DEFAULT_SUBSTATION = 'LOAD_DEFAULT_SUBSTATION'

export const LOAD_LOGS = 'LOAD_LOGS'

export const LOAD_DOCUMENTS = 'LOAD_DOCUMENTS'
export const LOAD_DOCUMENT = 'LOAD_DOCUMENT'

export const LOAD_MAINTENANCE_DETAILS = 'LOAD_MAINTENANCE_DETAILS'
export const LOAD_MAINTENANCE_QUESTIONS = 'LOAD_MAINTENANCE_QUESTIONS'
export const ADD_MAINTENANCE = 'ADD_MAINTENANCE'

export const ERROR = 'ERROR'